import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./(layouts)/navbar";
import Sidebar from "./(layouts)/sidebar";

const open_sans = Open_Sans({
  subsets: ["latin"],
  style: ["normal"],
  weight: ["400", "500", "700", "800"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${open_sans.className} flex w-full h-screen overflow-hidden`}
      >
        <Sidebar />
        <div className="w-full">
          <Navbar />
          <main className="w-full h-full">{children}</main>
        </div>
      </body>
    </html>
  );
}
